from st_pages import Page
to_show_pages =[
        Page("home.py", "Login", "🏠"),
        Page("pages/1_Profil.py", "Profil", "👤"),
        Page("pages/2_Coach.py", "Coach", ":teacher:"),
        Page("pages/3_Gespeichert.py", "Meine Sammlung", ":books:"),
        Page("pages/coach_Entlastungsangebote.py", "Entlastungsangebote"),
        Page("pages/coach_Vorsorgeauftrag.py", "Vorsorgeauftrag"),
        Page("pages/coach_Urteilsfaehigkeit.py", "Urteilsfaehigkeit"),
        Page("pages/coach_Angenehme Aktivitäten gestalten.py", "Angenehme Aktivitaeten gestalten"),
        Page("pages/coach_An- und Auskleiden.py", "An- und Auskleiden"),
        Page("pages/coach_Patientenverfuegung.py", "Patientenverfuegung"),
        Page("pages/coach_Zähneputzen.py", "Zaehneputzen"),
        Page("pages/coach_Körperpflege und Toilette.py", "Koerperpflege und Toilette"),
        Page("pages/coach_Sexualität.py", "Sexualitaet"),
        Page("pages/coach_Weglaufen.py", "Weglaufen"),
        Page("pages/coach_Essen und Trinken.py", "Essen und Trinken"),
        Page("pages/coach_Inkontinenz.py", "Inkontinenz"),
        Page("pages/coach_Abklärung und Diagnose.py", "Abklaerung und Diagnose"),
        Page("pages/coach_Finanzielle Ansprueche.py", "Finanzielle Ansprueche"),
        Page("pages/coach_Autofahren.py", "Autofahren"),
        Page("pages/coach_Schlafstörungen.py", "Schlafstoerungen"),
        Page("pages/coach_Schwierige Gesprächssituationen.py", "Schwierige Gespraechssituationen"),
        Page("pages/coach_Schmerzen.py", "Schmerzen"),
        Page("pages/coach_Umgang mit Aggressionen.py", "Umgang mit Aggressionen"),
        Page("pages/coach_Wohnanpassungen und Hilfsmittel.py", "Wohnanpassungen und Hilfsmittel"),
        Page("pages/coach_Vorsorge und Finanzierung.py", "Vorsorge und Finanzierung"),
        Page("pages/coach_Behandlung.py", "Behandlung"),
        Page("pages/coach_Sich verständigen.py", "Sich verstaendigen"),
        Page("pages/coach_Unterstützung für Angehörige.py", "Unterstuetzung fuer Angehoerige"),
        Page("pages/coach_Nach der Diagnose.py", "Nach der Diagnose"),
        Page("pages/coach_Herausfordernde Situationen.py", "Herausfordernde Situationen"),
        Page("pages/coach_Krankheitswissen Demenz.py", "Krankheitswissen Demenz"),
        Page("pages/coach_Pflege und Betreuung.py", "Pflege und Betreuung"),
        Page("pages/coach_Alltag aktiv gestalten.py", "Alltag aktiv gestalten")
    ]

to_hide_pages = [
    "weglaufen",
    "Entlastungsangebote",
    "Vorsorgeauftrag",
    "Angenehme Aktivitaeten gestalten",
    "An- und Auskleiden",
    "Patientenverfuegung",
    "Zaehneputzen",
    "Koerperpflege und Toilette",
    "Sexualitaet",
    "Weglaufen",
    "Essen und Trinken",
    "Inkontinenz",
    "Abklaerung und Diagnose",
    "Finanzielle Ansprueche",
    "Autofahren",
    "Schlafstoerungen",
    "Schwierige Gespraechssituationen",
    "Schmerzen",
    "Umgang mit Aggressionen",
    "Wohnanpassungen und Hilfsmittel",
    "Vorsorge und Finanzierung",
    "Behandlung",
    "Sich verstaendigen",
    "Unterstützung für Angehoerige",
    "Nach der Diagnose",
    "Herausfordernde Situationen",
    "Krankheitswissen Demenz",
    "Pflege und Betreuung",
    "Alltag aktiv gestalten",
    "Urteilsfaehigkeit",
    "Patientenverfuegung",
    "Sich verstaendigen",
    "Unterstuetzung fuer Angehoerige",
]

emoji_dict = {
    "Angenehme Aktivitäten gestalten": "🌼",
    "Wohnanpassungen und Hilfsmittel": "🏡",
    "Umgang mit Aggressionen": "😡",
    "Schlafstörungen": "😴",
    "Weglaufen": "🏃",
    "Sexualität": "💏",
    "Schmerzen": "😣",
    "Abklärung und Diagnose": "🏥",
    "Autofahren": "🚗",
    "Vorsorge und Finanzierung": "💰",
    "Behandlung": "💉",
    "Körperpflege und Toilette": "🛁",
    "An- und Auskleiden": "👕",
    "Essen und Trinken": "🍴",
    "Inkontinenz": "🚽",
    "Zähneputzen": "🦷",
    "Achtsamkeitsübungen": "🧘",
    "Schwierige Gesprächssituationen": "💬",
    "Entlastungsangebote": "🆘",
    "Finanzielle Ansprüche": "💰",
    "Patientenverfügung": "📄",
    "Urteilsfähigkeit": "🧠",
    "Vorsorgeauftrag": "📝",
    "Testament": "📜",
}