
to_hide_pages = [
    "Weglaufen",
    "Entlastungsangebote",
    "Vorsorgeauftrag",
    "Angenehme Aktivitaeten gestalten",
    "An- und Auskleiden",
    "Patientenverfuegung",
    "Zaehneputzen",
    "Koerperpflege und Toilette",
    "Sexualitaet",
    "Weglaufen",
    "Essen und Trinken",
    "Inkontinenz",
    "Abklaerung und Diagnose",
    "Finanzielle Ansprueche",
    "Autofahren",
    "Schlafstoerungen",
    "Schwierige Gespraechssituationen",
    "Schmerzen",
    "Umgang mit Aggressionen",
    "Wohnanpassungen und Hilfsmittel",
    "Vorsorge und Finanzierung",
    "Behandlung",
    "Sich verstaendigen",
    "Unterstützung für Angehoerige",
    "Nach der Diagnose",
    "Herausfordernde Situationen",
    "Krankheitswissen Demenz",
    "Pflege und Betreuung",
    "Alltag aktiv gestalten",
    "Urteilsfaehigkeit",
    "Patientenverfuegung",
    "Unterstuetzung fuer Angehoerige",
    "Achtsamkeitsuebungen",
    "Selbstfuersorge"
]

emoji_dict = {
    "Angenehme Aktivitäten gestalten": "🌼",
    "Wohnanpassungen und Hilfsmittel": "🏡",
    "Umgang mit Aggressionen": "😡",
    "Schlafstörungen": "😴",
    "Weglaufen": "🏃",
    "Sexualität": "💏",
    "Schmerzen": "😣",
    "Abklärung und Diagnose": "🏥",
    "Autofahren": "🚗",
    "Behandlung": "💉",
    "Körperpflege und Toilette": "🛁",
    "An- und Auskleiden": "👕",
    "Essen und Trinken": "🍴",
    "Inkontinenz": "🚽",
    "Zähneputzen": "🦷",
    "Achtsamkeitsübungen": "🧘",
    "Schwierige Gesprächssituationen": "💬",
    "Entlastungsangebote": "🆘",
    "Finanzielle Ansprüche": "💰",
    "Patientenverfügung": "📄",
    "Urteilsfähigkeit": "🧠",
    "Vorsorgeauftrag": "📝"
}