from st_pages import Page
to_show_pages =[
        Page("home.py", "Login", "🏠"),
        Page("pages/1_Profil.py", "Profil", "👤"),
        Page("pages/2_Coach.py", "Coach", ":teacher:"),
        Page("pages/3_Gespeichert.py", "Meine Sammlung", ":books:"),
        Page("helpers/coach_entlastungsangebote.py", "Entlastungsangebote"),
        Page("helpers/coach_vorsorgeauftrag.py", "Vorsorgeauftrag"),
        Page("helpers/coach_urteilsfaehigkeit.py", "Urteilsfaehigkeit"),
        Page("helpers/coach_angenehmeaktivitaetengestalten.py", "Angenehme Aktivitaeten gestalten"),
        Page("helpers/coach_anundauskleiden.py", "An- und Auskleiden"),
        Page("helpers/coach_patientenverfuegung.py", "Patientenverfuegung"),
        Page("helpers/coach_zaehneputzen.py", "Zaehneputzen"),
        Page("helpers/coach_koerperpflegeundtoilette.py", "Koerperpflege und Toilette"),
        Page("helpers/coach_sexualitaet.py", "Sexualitaet"),
        Page("helpers/coach_weglaufen.py", "Weglaufen"),
        Page("helpers/coach_essenundtrinken.py", "Essen und Trinken"),
        Page("helpers/coach_inkontinenz.py", "Inkontinenz"),
        Page("helpers/coach_abklaerungunddiagnose.py", "Abklaerung und Diagnose"),
        Page("helpers/coach_finanzielleansprueche.py", "Finanzielle Ansprueche"),
        Page("helpers/coach_autofahren.py", "Autofahren"),
        Page("helpers/coach_schlafstoerungen.py", "Schlafstoerungen"),
        Page("pages/coach_schwierigegespraechssituationen.py", "Schwierige Gespraechssituationen"),
        Page("helpers/coach_schmerzen.py", "Schmerzen"),
        Page("helpers/coach_umgangmitaggressionen.py", "Umgang mit Aggressionen"),
        Page("helpers/coach_wohnanpassungenundhilfsmittel.py", "Wohnanpassungen und Hilfsmittel"),
        Page("helpers/coach_vorsorgeundfinanzierung.py", "Vorsorge und Finanzierung"),
        Page("helpers/coach_behandlung.py", "Behandlung"),
        Page("helpers/coach_sichverstaendigen.py", "Sich verstaendigen"),
        Page("pages/coach_unterstuetzungfürangehoerige.py", "Unterstuetzung fuer Angehoerige"),
        Page("helpers/coach_nachderdiagnose.py", "Nach der Diagnose"),
        Page("helpers/coach_herausforderndesituationen.py", "Herausfordernde Situationen"),
        Page("helpers/coach_krankheitswissendemenz.py", "Krankheitswissen Demenz"),
        Page("helpers/coach_pflegeundbetreuung.py", "Pflege und Betreuung"),
        Page("helpers/coach_alltagaktivgestalten.py", "Alltag aktiv gestalten")
    ]

to_hide_pages = [
    "weglaufen",
    "Entlastungsangebote",
    "Vorsorgeauftrag",
    "Angenehme Aktivitaeten gestalten",
    "An- und Auskleiden",
    "Patientenverfuegung",
    "Zaehneputzen",
    "Koerperpflege und Toilette",
    "Sexualitaet",
    "Weglaufen",
    "Essen und Trinken",
    "Inkontinenz",
    "Abklaerung und Diagnose",
    "Finanzielle Ansprueche",
    "Autofahren",
    "Schlafstoerungen",
    "Schwierige Gespraechssituationen",
    "Schmerzen",
    "Umgang mit Aggressionen",
    "Wohnanpassungen und Hilfsmittel",
    "Vorsorge und Finanzierung",
    "Behandlung",
    "Sich verstaendigen",
    "Unterstützung für Angehoerige",
    "Nach der Diagnose",
    "Herausfordernde Situationen",
    "Krankheitswissen Demenz",
    "Pflege und Betreuung",
    "Alltag aktiv gestalten",
    "Urteilsfaehigkeit",
    "Patientenverfuegung",
    "Sich verstaendigen",
    "Unterstuetzung fuer Angehoerige",
]

emoji_dict = {
    "Angenehme Aktivitäten gestalten": "🌼",
    "Wohnanpassungen und Hilfsmittel": "🏡",
    "Umgang mit Aggressionen": "😡",
    "Schlafstörungen": "😴",
    "Weglaufen": "🏃",
    "Sexualität": "💏",
    "Schmerzen": "😣",
    "Abklärung und Diagnose": "🏥",
    "Autofahren": "🚗",
    "Vorsorge und Finanzierung": "💰",
    "Behandlung": "💉",
    "Körperpflege und Toilette": "🛁",
    "An- und Auskleiden": "👕",
    "Essen und Trinken": "🍴",
    "Inkontinenz": "🚽",
    "Zähneputzen": "🦷",
    "Achtsamkeitsübungen": "🧘",
    "Schwierige Gesprächssituationen": "💬",
    "Entlastungsangebote": "🆘",
    "Finanzielle Ansprüche": "💰",
    "Patientenverfügung": "📄",
    "Urteilsfähigkeit": "🧠",
    "Vorsorgeauftrag": "📝",
    "Testament": "📜",
}